### ISSUE TITLE
Temperature not being displayed (BME-280, temperate/humidity readings succeed).

### ISSUE THREAD

**Issue by jessesteinen** [appsmonkey/air.nodemcu.full#6]
Hi,

Temperature remains at 0. I added a few lines to the code to print measured values for temp/humidity to serial monitor, and that shows that the sensor is correctly reading these values. E.g.:

```
in.temperature 28.05
in.humidity 45.60
in.temperature feel 28.13
in.pressure 100754.80
in.altitude 47.58 (which is way off, but at least it's a valid value)
```

However in serial monitor (app is the same), I'm getting:
```
SENSES | Data points:
 - -  - -  - -  - -
1. DEVICE_TEMPERATURE (s17) : 0
2. AIR_PRESSURE (s3) : 0
3. AIR_PM1 (s4) : 9
4. AIR_PM2P5 (s5) : 13
5. AIR_PM10 (s6) : 15
6. AIR_AQI_RANGE (d3) : 1
7. AIR_PM2P5_RANGE (d4) : 1
8. AIR_PM10_RANGE (d5) : 0
```

My coding skills are lacking beyond some very basic debugging (printing to serial and such). Any help in debugging this would be much appreciated.

Thanks!
Jesse

**Comment by appsmonkey** [comment]
Your wiring and config are probably not matching. 
1. DEVICE_TEMPERATURE (s17) : 0
2. AIR_PRESSURE (s3) : 0

**Comment by ZarkoRunjevac** [comment]
Hi, 

there was error in BME_280.cpp, I have changed "air temperature" to "DEVICE_TEMPERATURE" so now you should receive correct values.

**Comment by jessesteinen** [comment]
Thank you, that fixed it.
